### ISSUE TITLE
debug_printcut

### ISSUE THREAD

**Issue by vgupta1** [IainNZ/JuMPeR.jl#52]
I know this is undocumented functionality, so maybe just ignore me:

But right now, this functionality relies on the idea that there is an internal cut-model being used to generate cuts.  (See e.g. oraclegen.jl around line 278)
Many cases I have closed-form ways of finding cuts.  Then the printing function chokes.

Error output below:
ERROR: type OptDirichlet has no field cut_model
 in debug_printcut at /Users/vishalgupta/.julia/v0.3/JuMPeR/src/oracle_gen.jl:278
 in generateCut at /Users/vishalgupta/Documents/Research/BayesDRO/AmbiguitySets/Experiments/../oracles.jl:49
 in generateCut at /Users/vishalgupta/Documents/Research/BayesDRO/AmbiguitySets/Experiments/../oracles.jl:25
 in solveRobust at /Users/vishalgupta/.julia/v0.3/JuMPeR/src/solve.jl:178
 in robustNews at /Users/vishalgupta/Documents/Research/BayesDRO/AmbiguitySets/Experiments/singleNewsVendor.jl:80
 in include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/vishalgupta/Documents/Research/BayesDRO/AmbiguitySets/Experiments/singleNewsVendor.jl, in expression starting on line 174

**Comment by IainNZ** [comment]
The `debug_printcut` function isn't meant to work in general, its designed for `GeneralOracle` only - its not meant to be used by other oracles. I'm not 100% sure what an oracle independent function would look like but its an option (it wouldn't have as much info though of course)

**Comment by vgupta1** [comment]
I mean... it works if you comment out the middle bit about the cut_model...

I would think that in debugging a cut, maybe all you really want is the
original (uncertain) constraint and the cut that was added?

VG
