### ISSUE TITLE
Keyword argument inconsistency

### ISSUE THREAD

**Issue by joeltay** [IainNZ/JuMPeR.jl#55]
In the documentation, prefer_cuts can be set to "true". But in the code, it seems to be set to "cuts".

**Comment by joeltay** [comment]
Just realized that cuts is Boolean, so this isn't the problem.

However, we did get an
exception on 1: ERROR: unrecognized keyword argument "prefer_cuts"
that was resolved by setting prefer_cuts as "true". Will reopen if I ever find out why.

**Comment by IainNZ** [comment]
Were you maybe still using solveRobust?

**Comment by joeltay** [comment]
Nope. Call was:
status = solve(m, suppress_warnings=true, prefer_cuts=true)
when we got the error.
