### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by emo7bf** [IainNZ/JuMPeR.jl#63]
The documentation at `doc/index.md` references `addEllipseConstraint`, which was removed in 44d63af in favor of `norm2`. As a new user, this tripped me up - should probably be updated :smile:

**Comment by IainNZ** [comment]
They're very out of date right now, I've been making big changes due to
updates to JuMP and because I'm writing up my PhD thesis. Once that's done
in a week or so I'll update it all.

**Comment by yeesian** [comment]
Apart from the link to the docs based on the gh-pages branch in the description, the docs are all up-to-date (as of this comment).

**Comment by IainNZ** [comment]
This was fixed a while ago
