### ISSUE TITLE
second-order conic constraint in uncertainty set

### ISSUE THREAD

**Issue by brad-sturt** [IainNZ/JuMPeR.jl#65]
I see in in [`src/uncsets_basic.jl`](https://github.com/IainNZ/JuMPeR.jl/blob/master/src/uncsets_basic.jl#L63-L71) that JuMPeR currently supports affine inequalities and `norm(x) <= const` where `x` is uncertain.

I am looking to use JuMPeR to handle uncertain sets with `norm(x) <= y` constraints, where `x` and `y` are both uncertain. 

1) Is this something that is doable in the current structure of the code?

2) What parts of the code would likely need modification?

**Comment by brad-sturt** [comment]
(by "modification", I of course mean that I would do the work)

**Comment by yeesian** [comment]
It's [already supported](https://github.com/IainNZ/JuMPeR.jl/blob/e161a36abfd541926db9d7591eb6e3ae6ec9bdc4/test/uncsets_basic_L2.jl#L122). Although if there's any further enhancements you're interested in supporting, a PR will be welcome (:

**Comment by yeesian** [comment]
Oh my bad, you're looking for the rhs to also be an uncertain variable. Anyhow, I'd recommend going through https://github.com/IainNZ/JuMPeR.jl/blob/e161a36abfd541926db9d7591eb6e3ae6ec9bdc4/src/robustmacro.jl#L395-L434.
