### ISSUE TITLE
Extract affine policy coefficients

### ISSUE THREAD

**Issue by joeltay** [IainNZ/JuMPeR.jl#66]
After solving a model with affine-adaptive variables, how do we extract the coefficients of that affine policy? getvalue doesn't seem to work on adaptive variables.

**Comment by IainNZ** [comment]
Hey Joel! No way to do it right now, but I think `getvalue` on an adaptive variable could possibly return something sensible in this case. It'd just need a bit more book keeping. Maybe give adding it a try? I can review the pull request.

**Comment by joeltay** [comment]
Thanks, I'll have a look!

**Comment by joeltay** [comment]
Not going to have time to work on this for a while, in case anyone else who is interested sees this :/
