### ISSUE TITLE
Error when solving problem with uncertain integer variables

### ISSUE THREAD

**Issue by brad-sturt** [IainNZ/JuMPeR.jl#72]
I am not sure this is a bug, but I was surprised to get a `LoadError: Integer uncertain parameters not supported in reformulation` when I run the following code: 
```
using JuMP, Gurobi, JuMPeR
model= RobustModel()
@variable(model, obj >= 0)
@uncertain(model, x[1:2], Bin)
@constraint(model, x[1] + x[2] == 1)
@constraint(model, obj <= 2*x[1] + x[2])
@objective(model, Max, obj)
solve(model,prefer_cuts=false)
```
I expected that JuMPeR would not be trying reformulation, and instead just cut on the different combinations of `x[1]` and `x[2]`. 

Is this a bug? Or, does my example fall into some broader class of problems that are not always solvable via adding cuts (and hence JuMPeR isn't attempting to solve it)?

I have looked at the docs, and saw
```
# You can even define binary uncertain parameters - although you might not
# be able to solve the resulting problem with all possible some methods!
# Also, note the use of an arbitrary index set.
highways = [:I90, :I93, :I95]
@uncertain(rm, blocked[highways], Bin)
```
Is this comment elaborated on anywhere in the code? 

Should setting `prefer_cuts` to `true` solve this problem? If so, is there a reason JuMPeR doesn't simply try cuts by default?

Thanks!

**Comment by IainNZ** [comment]
You can't reformulate an uncertainty set with integer variables, of course.

The default behaviour is reformulation - thus, you must specify cuts if you have an integer uncertainty set. To stop a silent mathematical error, I have that error message.

The reason it doesn't then auto change to cuts is the principle of least surprise - the choices are warning-then-do-cuts, or error, and I prefer errors to warnings.

**Comment by brad-sturt** [comment]
Great, thanks Iain!
