### ISSUE TITLE
JuMPeR not working in Julia PRO

### ISSUE THREAD

**Issue by gavelasq** [IainNZ/JuMPeR.jl#73]
I could not install JuMPeR using Julia PRO. The following message appears: "unsatisfiable package requirements detected: no feasible  version could be found for package: JuMP" When I try to update JuMP I get the following messsage: " Package JuMP was set to version 0.15.0, but a higher version 0.15.1 exists.
The update is prevented by explicit requirements constraints. Edit your REQUIRE file to change this"

**Comment by IainNZ** [comment]
JuMPeR hasn't been updated to work with JuMP 0.15. You could pin JuMP to a 0.14 release and run Pkg.update, I think that'd do it.

**Comment by gavelasq** [comment]
I tried that but didn't work. It started to have version issues with other packages so instead I installed Julia and Atom separately. No problems.
