### ISSUE TITLE
Implement adding constraints on uncertain parameters for the BudgetUncertaintySet

### ISSUE THREAD

**Issue by gavelasq** [IainNZ/JuMPeR.jl#80]
I need this for my research, but I am not familiar with creating and changing packages. Could someone help me with this?. I am trying to implement the Dunning's adaptive partitions algorithm with BudgetUncertaintySet.

**Comment by gavelasq** [comment]
This seems to work:
        
us = JuMPeR.BasicUncertaintySet()
@constraint(us, norm(ξ, 1) <= Γ)

is this ok?

**Comment by IainNZ** [comment]
Yes thats great, except you will also want to limit individual perturbations to +- 1.
The BudgetUncertaintySet is mainly a demonstration of making a custom set.
